[package]
name = "podnab"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[dependencies.gtk]
package = "gtk4"
version = "0.4.6"
features = ["v4_4"]